#pragma once

#define _USE_MATH_DEFINES

#include <SimpleMath.h>
#include <string>
#include <d3d11.h>
#include <WICTextureLoader.h>
#include <DirectXColors.h>
#include <cmath>
#include <d2d1.h>
#include <list>
#include <algorithm>
#include <wrl.h>
#include <io.h>
#include <Fcntl.h>
#include <consoleapi.h>
#include <iostream>
#include <math.h>
#include <time.h>
#include <fstream>
#include <locale.h>
#include <wchar.h>
#include <map>
#include <GamePad.h>
#include <Keyboard.h>
#include <memory>
#include <Model.h>
#include <Effects.h>
#include <CommonStates.h>
#include <PrimitiveBatch.h>
#include <SpriteFont.h>
#include <Windows.h>
#include <iterator>
#include <stdlib.h>
#include <thread>
#include <vector>
#include <windows.h>
#include <MMREG.H>
#include <Msacm.h>
#include <tchar.h>
#include <mmsystem.h>
#include <dSound.h>
#include <dwrite.h>
#include <exception>
#include <Shlwapi.h>
